Features/0122b
FrontStudy/React-Admin pull request #4
Opened 2024-01-30 02:49 UTC by 3-yellow-1

2024-01-30 03:04 UTC, 6cessfuldev requested changes
StrictMode가 BrowserRouter를 포함해서 제일 밖에서 감싸는게 좋지 않을까요!?

2024-01-30 03:04 UTC, 6cessfuldev commented on src/index.js
> +  <BrowserRouter>
기능적으로 큰 차이는 아닌데 보통 StrictMode가 가장 밖에서 다 감싸는 식으로 코드를 짠다고 하더라구요..! BrowserRouter 포함해서요!

2024-01-30 04:04 UTC, 3-yellow-1 commented on src/index.js
> +  <BrowserRouter>
네 그게 좋을거 같아요! 수정해둘게요!!

2024-01-30 04:06 UTC, 6cessfuldev approved these changes
good~!

2024-01-31 01:00 UTC, Jun2313 approved these changes

2024-02-02 09:02 UTC, merged